# Generated by Django 4.0 on 2022-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insightsAnalyticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_files', models.FileField(blank=True, upload_to='files/')),
                ('keyword_file', models.FileField(blank=True, upload_to='files/')),
            ],
        ),
    ]
