# Generated by Django 4.0 on 2022-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='socialAnalyticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_file', models.FileField(blank=True, upload_to='files/')),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('no_of_tweets', models.IntegerField(blank=True)),
                ('consumer_key', models.CharField(blank=True, max_length=500, null=True)),
                ('access_token', models.CharField(blank=True, max_length=500, null=True)),
                ('consumer_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('access_token_secret', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
