# Generated by Django 4.0 on 2022-05-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsanalyticsmodel',
            name='keyword_file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
