# Generated by Django 4.0 on 2022-05-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='textAnalyticsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(blank=True, upload_to='files/')),
                ('keyword_file', models.FileField(blank=True, upload_to='files/')),
                ('keywords', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
