# Generated by Django 4.0 on 2022-05-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textanalyticsmodel',
            name='keyword_file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='textanalyticsmodel',
            name='report_file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
