# Generated by Django 4.0 on 2022-05-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_analytics', '0003_rename_report_file_textanalyticsmodel_report_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textanalyticsmodel',
            name='keyword_file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='textanalyticsmodel',
            name='report_files',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
